#!/usr/bin/env python3
"""Generate docs/reference/programs/ from the --help output of every built program.

Usage: python3 scripts_cmake/gen_program_reference.py <build-dir> [<docs/reference/programs dir>]

One Markdown page per program, grouped by the directory the program lives in
(src/Programs, FQHE/.../FQHEOnSphere, FTI/.../FCI, Spin, QuantumDots, Analysis),
plus an index. Pages are generated: do not edit them by hand -- edit the
program's option definitions and regenerate. A hand-written manual for a
program, if one exists at manuals/<Program>.md (adapted from the upstream
wiki), is linked from the generated page.

Programs without an option parser (they read argv positionally, or run
without arguments) are listed on the index with the reason instead of being
executed; the list mirrors tests/CMakeLists.txt.
"""
import os, re, subprocess, sys
from pathlib import Path

NO_OPTION_PARSER = {
    "QHEBosons": "reads argv[1] as a particle count; no option parser",
    "MultipleSpinChain": "reads argv[1] as spins per chain; no option parser",
    "TestDiagHamVectors": "benchmark with no arguments; runs for minutes",
    "EvaluateBroadening": "checks its required --input before --help, so --help exits -1",
}
MARK = "<!-- generated by scripts_cmake/gen_program_reference.py; do not edit -->"


def find_programs(build):
    progs = []
    for dp, dn, fn in os.walk(build):
        dn[:] = [d for d in dn if d not in ("CMakeFiles", "tests", "Testing", "_deps")]
        rel = os.path.relpath(dp, build)
        if "/Programs" not in "/" + rel and not rel.endswith("Tools/Analysis"):
            continue
        for f in fn:
            p = os.path.join(dp, f)
            if os.access(p, os.X_OK) and not f.endswith((".o", ".a", ".txt", ".cmake", ".ninja", ".make")) and os.path.isfile(p):
                progs.append((rel, f, p))
    return sorted(progs)


def help_text(path):
    try:
        r = subprocess.run([path, "--help"], capture_output=True, text=True, timeout=30, cwd="/tmp")
        return (r.stdout + r.stderr).strip(), r.returncode
    except subprocess.TimeoutExpired:
        return "", "timeout"


def group_of(rel):
    parts = rel.split("/")
    module = parts[0]
    leaf = parts[-1]
    if module == "src":
        return "core", "src/Programs"
    if leaf == "Programs":
        return module, f"{module}/src/Programs"
    return module, f"{module}/src/.../{leaf}"


def main(build, out):
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    for old in out.rglob("*.md"):
        if old.name != "README.md" and "manuals" not in old.parts:
            old.unlink()
    progs = find_programs(build)
    index = {}
    n_ok = n_skip = n_fail = 0
    for rel, name, path in progs:
        module, group = group_of(rel)
        leaf = rel.split("/")[-1]
        page_dir = out / (leaf if leaf != "Programs" else module if module != "src" else "core")
        page_dir.mkdir(exist_ok=True)
        page = page_dir / f"{name}.md"
        manual = out / "manuals" / f"{name}.md"
        lines = [MARK, f"# {name}", "", f"Module: **{module}** · directory: `{group.replace('.../', '')}` · binary: `{rel}/{name}`", ""]
        if manual.exists():
            lines += [f"Manual: [{name} (from the DiagHam wiki)](../manuals/{name}.md)", ""]
        if name in NO_OPTION_PARSER:
            lines += [f"_No `--help` output: {NO_OPTION_PARSER[name]}._", ""]
            status = "no option parser"
            n_skip += 1
        else:
            text, rc = help_text(path)
            if rc != 0 or not text:
                lines += [f"_`--help` exited with {rc}; output, if any, follows._", ""]
                status = f"help exit {rc}"
                n_fail += 1
            else:
                status = "ok"
                n_ok += 1
            lines += ["```text", text, "```", ""]
        page.write_text("\n".join(lines))
        index.setdefault((module, group, page_dir.name), []).append((name, status, manual.exists()))
    # index
    idx = [MARK, "# Program reference", "",
           f"Generated from `--help` of every program in the build (`{os.path.basename(build)}` preset): "
           f"{n_ok} with full option listings, {n_skip} without an option parser, {n_fail} whose `--help` failed. "
           "Pages are regenerated with `python3 scripts_cmake/gen_program_reference.py <build-dir>`; "
           "hand-written manuals adapted from the DiagHam wiki live in `manuals/` and are linked where they exist.", ""]
    for (module, group, dname) in sorted(index):
        entries = index[(module, group, dname)]
        idx += [f"## {module}: `{group}` ({len(entries)} programs)", ""]
        for name, status, has_manual in sorted(entries):
            extra = "" if status == "ok" else f" — _{status}_"
            man = " · [manual](manuals/%s.md)" % name if has_manual else ""
            idx.append(f"- [{name}]({dname}/{name}.md){extra}{man}")
        idx.append("")
    (out / "README.md").write_text("\n".join(idx))
    print(f"programs: {len(progs)}  ok: {n_ok}  no-parser: {n_skip}  failed: {n_fail}  -> {out}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(os.path.abspath(sys.argv[1]), sys.argv[2] if len(sys.argv) > 2 else "docs/reference/programs")
