#!/usr/bin/env python3
"""Write the `nav:` section of mkdocs.yml from the docs/ tree.

    python3 scripts_cmake/gen_mkdocs_nav.py            # rewrites mkdocs.yml in place
    python3 scripts_cmake/gen_mkdocs_nav.py --check    # exit 1 if mkdocs.yml is stale

The site is the docs/ knowledge base (Diátaxis: tutorials, how-to, reference,
explanation, plus history and drafts). Hand-written pages are listed in the
navigation with their H1 as title; the 700+ generated program pages are not
listed (they are reachable from the program index and through search).
Everything between "# nav-begin" and "# nav-end" in mkdocs.yml is replaced.
"""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MKDOCS = ROOT / "mkdocs.yml"

SECTIONS = [  # (title, directory, subdirectories listed as sub-sections)
    ("Tutorials", "tutorials", []),
    ("How-to guides", "how-to", ["build", "develop"]),
    ("Reference", "reference", []),
    ("Explanation", "explanation", []),
    ("History", "history", ["release-notes"]),
    ("Upstream reports", "upstream-reports", []),
    ("Drafts", "drafts", []),
]
SUBSECTION_TITLES = {"build": "Build", "develop": "Develop", "release-notes": "Release notes"}


def title_of(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            t = line[2:].strip()
            t = re.sub(r"^Tutorial: ", "", t)
            return t.replace("'", "''")
    return path.stem


def pages(directory):
    out = []
    readme = directory / "README.md"
    if readme.exists():
        out.append(readme)
    out += sorted(p for p in directory.glob("*.md") if p.name != "README.md" and p.name != "INDEX.md")
    index = directory / "INDEX.md"
    if index.exists():
        out.insert(0, index)
    return out


def rel(p):
    return p.relative_to(DOCS).as_posix()


def nav_lines():
    lines = ["nav:", "  - Home: README.md"]
    for title, d, subs in SECTIONS:
        directory = DOCS / d
        if not directory.exists():
            continue
        lines.append(f"  - {title}:")
        for p in pages(directory):
            lines.append(f"      - '{title_of(p)}': {rel(p)}")
        for sub in subs:
            sd = directory / sub
            if not sd.exists():
                continue
            lines.append(f"      - {SUBSECTION_TITLES.get(sub, sub)}:")
            for p in pages(sd):
                lines.append(f"          - '{title_of(p)}': {rel(p)}")
        if d == "reference":
            lines.append("      - Programs:")
            lines.append("          - 'Program reference (all 603, generated)': reference/programs/README.md")
            manuals = DOCS / "reference" / "programs" / "manuals"
            if manuals.exists():
                lines.append(f"          - 'Manuals from the DiagHam wiki ({len(list(manuals.glob('*.md')))})': reference/programs/manuals/README.md")
        if d == "drafts":
            stubs = DOCS / "drafts" / "manual-stubs"
            if stubs.exists():
                lines.append("      - 'Parked wiki program pages': drafts/manual-stubs/INDEX.md")
    return "\n".join(lines) + "\n"


def main():
    text = MKDOCS.read_text(encoding="utf-8")
    begin, end = "# nav-begin", "# nav-end"
    a, b = text.index(begin), text.index(end)
    new = text[:a] + begin + " (generated by scripts_cmake/gen_mkdocs_nav.py; do not edit)\n" + nav_lines() + text[b:]
    if "--check" in sys.argv:
        if new != text:
            print("mkdocs.yml nav is stale: run python3 scripts_cmake/gen_mkdocs_nav.py")
            sys.exit(1)
        print("mkdocs.yml nav up to date")
        return
    MKDOCS.write_text(new, encoding="utf-8")
    print(f"mkdocs.yml nav written ({nav_lines().count(chr(10))} lines)")


if __name__ == "__main__":
    main()
