#!/usr/bin/env python3
"""Report which programs the test suite actually exercises, and how.

Usage: tests/coverage.py <build-dir> [--write docs/reference/test-coverage.md] [--manifest tests/manifest.txt]

Reads `ctest --show-only=json-v1` from the build directory. For every
program of the build it records the labels of the tests that run it:

  physics     an answer known independently of DiagHam (analytic, exact
              counting, an independent solver) is checked
  crosscheck  two DiagHam programs, or two algorithms, must agree
  regression  a spectrum saved from an earlier build must be reproduced
              (detects change, not correctness)
  smoke       `--help` exits 0 (linking and option parsing only)

A program with only a smoke test is counted as *untested physics*; the
numbers this script prints are the ones the documentation may quote.
"""
import argparse, json, os, re, subprocess, sys
from collections import defaultdict
from pathlib import Path

KINDS = ("physics", "crosscheck", "regression", "smoke")


def ctest_json(build_dir):
    out = subprocess.run(["ctest", "--show-only=json-v1"], cwd=build_dir, check=True,
                         capture_output=True, text=True).stdout
    return json.loads(out)


def programs_of(test, build_dir, helpers):
    """Executables under the build tree that a test runs (main and reference programs)."""
    progs = set()
    for arg in test.get("command", []):
        for m in re.finditer(r"(?:^|=)(/[^\s|;]+)", arg):
            p = m.group(1)
            if os.path.isfile(p) and os.access(p, os.X_OK) and os.path.abspath(p).startswith(build_dir) \
                    and os.path.basename(p) not in helpers:
                progs.add(os.path.basename(p))
    return progs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("build_dir")
    ap.add_argument("--write", help="markdown report path")
    ap.add_argument("--manifest", help="write the sorted list of test names here")
    ap.add_argument("--programs-dir", default="docs/reference/programs",
                    help="generated program reference (for the module of each program)")
    a = ap.parse_args()

    build_dir = os.path.abspath(a.build_dir)
    data = ctest_json(a.build_dir)
    tests = data["tests"]
    names = sorted(t["name"] for t in tests)
    if a.manifest:
        Path(a.manifest).write_text("\n".join(names) + "\n")

    module_of = {}
    for p in Path(a.programs_dir).glob("*/*.md"):
        if p.parent.name != "manuals":
            module_of[p.stem] = p.parent.name

    cov = defaultdict(lambda: defaultdict(set))   # program -> kind -> test names
    by_label = defaultdict(int)
    for t in tests:
        labels = set()
        for prop in t.get("properties", []):
            if prop["name"] == "LABELS":
                labels = set(prop["value"])
        for l in labels:
            by_label[l] += 1
        kinds = [k for k in KINDS if k in labels]
        for prog in programs_of(t, build_dir, {"check_spectrum"}):
            for k in kinds:
                cov[prog][k].add(t["name"])
    # programs known from the reference but without any test at all
    all_programs = set(module_of) | set(cov)

    def has(p, k):
        return bool(cov[p][k]) if p in cov else False
    n_phys = sum(1 for p in all_programs if has(p, "physics"))
    n_cross = sum(1 for p in all_programs if has(p, "crosscheck"))
    n_regr = sum(1 for p in all_programs if has(p, "regression"))
    n_any_physics = sum(1 for p in all_programs if has(p, "physics") or has(p, "crosscheck") or has(p, "regression"))
    n_smoke_only = sum(1 for p in all_programs if has(p, "smoke") and not (has(p, "physics") or has(p, "crosscheck") or has(p, "regression")))
    n_none = sum(1 for p in all_programs if not any(has(p, k) for k in KINDS))

    lines = []
    lines.append("<!-- generated by tests/coverage.py; do not edit -->")
    lines.append("# Test coverage by program")
    lines.append("")
    lines.append("Purpose: say honestly which of the programs have their physics checked, and how; the `--help` smoke test is not a physics check and is not counted as one.")
    lines.append(f"Source: `ctest --show-only=json-v1` of the build; {len(tests)} tests, {len(all_programs)} programs. Regenerate with `python3 tests/coverage.py <build-dir> --write docs/reference/test-coverage.md`.")
    lines.append("")
    lines.append("| Programs with… | Count | Of |")
    lines.append("|---|---:|---:|")
    lines.append(f"| a `physics` test (answer known independently of DiagHam) | {n_phys} | {len(all_programs)} |")
    lines.append(f"| a `crosscheck` test (agrees with another program or algorithm) | {n_cross} | {len(all_programs)} |")
    lines.append(f"| a `regression` test (reproduces a saved spectrum; change detection only) | {n_regr} | {len(all_programs)} |")
    lines.append(f"| **any of the three** | **{n_any_physics}** | {len(all_programs)} |")
    lines.append(f"| only a `smoke` test (`--help`) — physics untested | {n_smoke_only} | {len(all_programs)} |")
    lines.append(f"| no test at all | {n_none} | {len(all_programs)} |")
    lines.append("")
    lines.append("Tests by label: " + ", ".join(f"`{l}` {n}" for l, n in sorted(by_label.items())) + ".")
    lines.append("")
    lines.append("## Programs with a physics, crosscheck or regression test")
    lines.append("")
    lines.append("| Program | Module | physics | crosscheck | regression | Tests |")
    lines.append("|---|---|:-:|:-:|:-:|---|")
    for p in sorted(all_programs):
        if not (has(p, "physics") or has(p, "crosscheck") or has(p, "regression")):
            continue
        tests_list = sorted(set().union(*(cov[p][k] for k in ("physics", "crosscheck", "regression"))))
        lines.append(f"| {p} | {module_of.get(p, '?')} | {'✓' if has(p,'physics') else ''} | {'✓' if has(p,'crosscheck') else ''} | {'✓' if has(p,'regression') else ''} | " + "<br>".join(f"`{t}`" for t in tests_list) + " |")
    lines.append("")
    lines.append("## Smoke-only programs, by module")
    lines.append("")
    per_mod = defaultdict(list)
    for p in sorted(all_programs):
        if has(p, "smoke") and not (has(p, "physics") or has(p, "crosscheck") or has(p, "regression")):
            per_mod[module_of.get(p, "?")].append(p)
    for m in sorted(per_mod):
        lines.append(f"- **{m}** ({len(per_mod[m])}): " + ", ".join(per_mod[m]))
    lines.append("")
    if n_none:
        lines.append("## Programs with no test at all")
        lines.append("")
        lines.append(", ".join(sorted(p for p in all_programs if not any(has(p, k) for k in KINDS))))
        lines.append("")
    report = "\n".join(lines)
    if a.write:
        Path(a.write).write_text(report)
    print(f"programs {len(all_programs)}: physics {n_phys}, crosscheck {n_cross}, regression {n_regr}, any {n_any_physics}, smoke-only {n_smoke_only}, none {n_none}; tests {len(tests)}")


if __name__ == "__main__":
    main()
