# ----------------------------------------------------------------------------
# Regression tests (label: regression): the program must reproduce the
# spectrum saved from an earlier build of this repository. This detects
# CHANGE, not correctness -- a reference is what r4493 printed, right or
# wrong. Cases: tests/data/regression/cases.txt; references generated by
#   python3 tests/regression_reference.py build/default --write
# (and --only <case> from a build with GSL for the GSL case). Regenerate
# only for an understood, intended change, and say so in the commit.
# ----------------------------------------------------------------------------
set(regression_data ${DIAGHAM_TEST_DATA}/regression)
file(STRINGS ${regression_data}/cases.txt regression_cases)
foreach(line ${regression_cases})
    if(line MATCHES "^#" OR line STREQUAL "")
        continue()
    endif()
    string(REPLACE "|" ";" parts "${line}")
    list(LENGTH parts n)
    list(GET parts 0 name)
    list(GET parts 1 target)
    list(GET parts 2 glob)
    list(GET parts 3 args)
    string(STRIP "${name}" name)
    string(STRIP "${target}" target)
    string(STRIP "${glob}" glob)
    string(STRIP "${args}" args)
    string(REPLACE "@DATA@" "${regression_data}" args "${args}")
    separate_arguments(args UNIX_COMMAND "${args}")
    if(n GREATER 4)
        list(GET parts 4 condition)
        string(STRIP "${condition}" condition)
        if(NOT ${condition})
            continue()
        endif()
    endif()
    if(NOT EXISTS ${regression_data}/${name}.dat)
        message(WARNING "regression: no reference for ${name}, test not registered")
        continue()
    endif()
    string(REGEX MATCH "^[A-Za-z0-9]+" module "${target}")
    if(glob STREQUAL "program.log")
        set(check numbers @OUTPUT@ ${regression_data}/${name}.dat 1e-9)
    else()
        set(check spectrum @OUTPUT@ -1 ${regression_data}/${name}.dat -1 1e-9)
    endif()
    diagham_physics_test(regression.${name}
        PROGRAM ${target} ARGS ${args} OUTPUT "${glob}"
        CHECK ${check}
        LABELS ${module})
    # diagham_physics_test labels physics; a regression is not one
    set_tests_properties(regression.${name} PROPERTIES LABELS "regression;${module}")
endforeach()

# known defect U31: FCICheckerboardLatticeModel without --single-band (the two-band model)
# segfaults after "start" for every size tried; WILL_FAIL until it is fixed.
diagham_physics_test(knownbug.fci.checkerboard.two_band_model_segfault
    PROGRAM FCI_FCICheckerboardLatticeModel
    ARGS -p 3 -x 3 -y 3 --flat-band --full-diag 5000
    OUTPUT "fermions_checkerboardlattice_*_gx_*.dat"
    CHECK count @OUTPUT@ -1 0 1e-10 0
    WILL_FAIL LABELS fci)
