#!/usr/bin/env python3
"""Exact Hilbert-space dimensions, counted without DiagHam.

Every function here enumerates or counts Fock states combinatorially (pure
Python, no numpy). The results are the expected values of the `physics`
dimension tests in tests/CMakeLists.txt: the committed files under
tests/data/dimensions/ are generated by

    python3 tests/oracles/dimensions.py --write tests/data/dimensions

and `python3 tests/oracles/dimensions.py --check tests/data/dimensions`
regenerates them into memory and fails if any committed file differs
(registered as selftest.dimension_oracle when Python 3 is available).

Conventions (matching what the programs print):
- sphere: 2S+1 orbitals with 2m = -2S, -2S+2, ..., 2S; the "Lz =" line lists
  the number of states with 2Lz = 0, 2, 4, ... up to the maximum; the "L ="
  line lists dim(L) = dim(Lz=L) - dim(Lz=L+1).
- torus: Nphi orbitals j = 0..Nphi-1; Ky = sum(j) mod Nphi. With magnetic
  translations (FQHETorusGetDimension) g = gcd(N, Nphi); the program labels
  sectors (k_x, k_y) with k_x, k_y in [0, g); k_y stands for the class of
  Ky values {k_y, k_y + g, ...}, and the k_x sectors are the eigenspaces of
  the translation T: j -> j + Nphi/g (order g) on the states of that Ky.
  Bosons carry no sign under T, so the k_x dimensions follow from Burnside's
  lemma; for fermions the sign of the sorting permutation is included (it
  is a fermionic Fock state property, not a DiagHam convention).
- FTI single band: Nx*Ny momentum orbitals (kx, ky); sector = total momentum
  mod (Nx, Ny).
- Hubbard: spin-1/2 fermions on Ns sites; with Sz conserved, 2Sz = total-spin.
- spin chains: N spins of length S, sector 2Sz.
- disk: orbitals m = 0, 1, 2, ...; sector = total Lz.
"""
import argparse, itertools, sys, os
from math import comb, gcd
from pathlib import Path


def fock_states(n, orbitals, fermion):
    """All occupation tuples of n particles on `orbitals` orbitals."""
    if fermion:
        return [tuple(c) for c in itertools.combinations(range(orbitals), n)]
    return [tuple(c) for c in itertools.combinations_with_replacement(range(orbitals), n)]


# ---- sphere -------------------------------------------------------------------
def sphere_lz_line(n, two_s, fermion):
    """'Lz = a b c ...' : states with 2Lz = 0, 2, ..., 2Lz_max."""
    counts = {}
    for st in fock_states(n, two_s + 1, fermion):
        two_lz = sum(2 * j - two_s for j in st)
        counts[two_lz] = counts.get(two_lz, 0) + 1
    two_lz_max = max(counts)
    return [counts.get(v, 0) for v in range(0 if two_lz_max % 2 == 0 else 1, two_lz_max + 1, 2)]


def sphere_l_line(lz_line):
    return [lz_line[i] - (lz_line[i + 1] if i + 1 < len(lz_line) else 0) for i in range(len(lz_line))]


def sphere_lz_dimension(n, two_s, two_lz, fermion):
    return sum(1 for st in fock_states(n, two_s + 1, fermion) if sum(2 * j - two_s for j in st) == two_lz)


# ---- torus ---------------------------------------------------------------------
def torus_ky_dimension(n, nphi, ky, fermion):
    return sum(1 for st in fock_states(n, nphi, fermion) if sum(st) % nphi == ky)


def _perm_sign(seq):
    """Sign of the permutation that sorts seq (distinct integers)."""
    seq = list(seq)
    sign = 1
    for i in range(len(seq)):
        for j in range(i + 1, len(seq)):
            if seq[i] > seq[j]:
                sign = -sign
    return sign


def torus_kxky_sectors(n, nphi, fermion):
    """{(kx, ky): dim} as FQHETorusGetDimension labels them (kx, ky in [0, g))."""
    g = gcd(n, nphi)
    shift = nphi // g
    import cmath
    out = {}
    for ky in range(g):
        states = [st for st in fock_states(n, nphi, fermion) if sum(st) % nphi == ky]
        # trace of T^t on this Ky space
        traces = []
        for t in range(g):
            tr = 0
            for st in states:
                moved = [(j + t * shift) % nphi for j in st]
                if sorted(moved) == list(st):
                    tr += _perm_sign(moved) if fermion else 1
            traces.append(tr)
        for kx in range(g):
            val = sum(traces[t] * cmath.exp(-2j * cmath.pi * kx * t / g) for t in range(g)) / g
            d = round(val.real)
            assert abs(val - d) < 1e-9, (n, nphi, kx, ky, val)
            out[(kx, ky)] = d
    return out


# ---- FTI single band ----------------------------------------------------------
def fti_sectors(n, nx, ny, boson):
    orbitals = [(kx, ky) for kx in range(nx) for ky in range(ny)]
    out = {}
    for st in fock_states(n, len(orbitals), not boson):
        kx = sum(orbitals[j][0] for j in st) % nx
        ky = sum(orbitals[j][1] for j in st) % ny
        out[(kx, ky)] = out.get((kx, ky), 0) + 1
    return out


# ---- Hubbard --------------------------------------------------------------------
def hubbard_dimension(n, nsites, two_sz=None):
    if two_sz is None:
        return comb(2 * nsites, n)
    nup = (n + two_sz) // 2
    return comb(nsites, nup) * comb(nsites, n - nup)


# ---- spin chains -------------------------------------------------------------------
def spin_chain_dimension(nspins, two_s, two_sz):
    counts = {0: 1}
    for _ in range(nspins):
        new = {}
        for v, c in counts.items():
            for m in range(-two_s, two_s + 1, 2):
                new[v + m] = new.get(v + m, 0) + c
        counts = new
    return counts.get(two_sz, 0)


# ---- disk ---------------------------------------------------------------------------
def disk_dimension(n, lz, fermion):
    if fermion:
        return sum(1 for c in itertools.combinations(range(lz + 1), n) if sum(c) == lz)
    return sum(1 for c in itertools.combinations_with_replacement(range(lz + 1), n) if sum(c) == lz)


# ---- the cases ----------------------------------------------------------------------
# name -> (description, list of expected stdout lines) or (description, count)
def cases():
    C = {}

    def sphere(name, n, two_s, fermion):
        lz = sphere_lz_line(n, two_s, fermion)
        C[name] = (f"{'fermions' if fermion else 'bosons'} N={n} 2S={two_s}: states per 2Lz=0,2,... then per L (dim(L)=dim(Lz=L)-dim(Lz=L+1)); total {sum(lz)*2-lz[0]} = C({two_s+1}{'' if fermion else '+'+str(n)+'-1'},{n})",
                   ["Lz = " + " ".join(map(str, lz)), "L = " + " ".join(map(str, sphere_l_line(lz)))])
    sphere("sphere_getdim_fermions_n4_2s9", 4, 9, True)
    sphere("sphere_getdim_fermions_n6_2s15", 6, 15, True)
    sphere("sphere_getdim_bosons_n4_2s6", 4, 6, False)
    sphere("sphere_getdim_bosons_n5_2s8", 5, 8, False)

    def torus(name, n, nphi, fermion):
        sec = torus_kxky_sectors(n, nphi, fermion)
        g = gcd(n, nphi)
        C[name] = (f"{'fermions' if fermion else 'bosons'} N={n} Nphi={nphi}: (k_x,k_y) sectors, g=gcd={g}, Burnside over T: j->j+{nphi//g}; sum over sectors x {nphi//g} = {sum(sec.values())*(nphi//g)}",
                   [f" (k_x = {kx}, k_y = {ky}) : {sec[(kx, ky)]}" for kx in range(g) for ky in range(g)])
    torus("torus_getdim_bosons_n3_nphi6", 3, 6, False)
    torus("torus_getdim_bosons_n4_nphi8", 4, 8, False)
    torus("torus_getdim_fermions_n3_nphi6", 3, 6, True)
    torus("torus_getdim_fermions_n4_nphi12", 4, 12, True)

    def fti(name, n, nx, ny, boson):
        sec = fti_sectors(n, nx, ny, boson)
        C[name] = (f"{'bosons' if boson else 'fermions'} N={n} on {nx}x{ny} momentum orbitals, single band, all sectors (FTIGetDimension --no-inversion); total {sum(sec.values())}",
                   [f"(kx={kx},ky={ky}) : {sec.get((kx, ky), 0)}" for kx in range(nx) for ky in range(ny)])
    fti("fti_getdim_fermions_n4_3x3", 4, 3, 3, False)
    fti("fti_getdim_bosons_n3_2x3", 3, 2, 3, True)
    fti("fti_getdim_fermions_n3_4x2", 3, 4, 2, False)

    C["hubbard_getdim_n4_sites4"] = ("spin-1/2 fermions, 4 on 4 sites, Sz free: C(8,4)", [f"Hilbert space dimension = {hubbard_dimension(4, 4)}"])
    C["hubbard_getdim_n4_sites4_sz0"] = ("4 on 4 sites, 2Sz=0: C(4,2)^2", [f"Hilbert space dimension = {hubbard_dimension(4, 4, 0)}"])
    C["hubbard_getdim_n3_sites4_sz1"] = ("3 on 4 sites, 2Sz=1: C(4,2)*C(4,1)", [f"Hilbert space dimension = {hubbard_dimension(3, 4, 1)}"])
    C["hubbard_getdim_n6_sites6_sz0"] = ("6 on 6 sites, 2Sz=0: C(6,3)^2", [f"Hilbert space dimension = {hubbard_dimension(6, 6, 0)}"])

    # counts (number of basis states printed)
    C["sphere_showbasis_fermions_n3_2s6_lz0"] = ("fermions N=3 2S=6 Lz=0 count", sphere_lz_dimension(3, 6, 0, True))
    C["sphere_showbasis_fermions_n4_2s9_lz0"] = ("fermions N=4 2S=9 Lz=0 count (the first 'Lz =' entry above)", sphere_lz_dimension(4, 9, 0, True))
    C["sphere_showbasis_bosons_n3_2s4_lz0"] = ("bosons N=3 2S=4 Lz=0 count", sphere_lz_dimension(3, 4, 0, False))
    # FQHETorusShowBasis uses magnetic translations: -x kx -y ky select one (k_x, k_y) sector
    C["torus_showbasis_fermions_n4_nphi12_kx0_ky0"] = ("fermions N=4 Nphi=12, sector (k_x=0, k_y=0) with magnetic translations (Burnside, fermion sign)", torus_kxky_sectors(4, 12, True)[(0, 0)])
    C["torus_showbasis_bosons_n3_nphi6_kx0_ky0"] = ("bosons N=3 Nphi=6, sector (k_x=0, k_y=0) with magnetic translations (Burnside)", torus_kxky_sectors(3, 6, False)[(0, 0)])
    C["disk_showbasis_fermions_n3_lz6"] = ("fermions N=3 Lz=6 on the disk: 3 distinct m>=0 summing to 6", disk_dimension(3, 6, True))
    C["disk_showbasis_fermions_n4_lz10"] = ("fermions N=4 Lz=10: 4 distinct m>=0 summing to 10", disk_dimension(4, 10, True))
    C["disk_showbasis_bosons_n3_lz6"] = ("bosons N=3 Lz=6: 3 m>=0 (repeats allowed) summing to 6", disk_dimension(3, 6, False))
    C["spin_showbasis_s1_2_n6_sz0"] = ("6 spins 1/2, Sz=0: C(6,3)", spin_chain_dimension(6, 1, 0))
    C["spin_showbasis_s1_2_n8_2sz2"] = ("8 spins 1/2, 2Sz=2: C(8,5)", spin_chain_dimension(8, 1, 2))
    C["spin_showbasis_s1_n4_sz0"] = ("4 spins 1, Sz=0", spin_chain_dimension(4, 2, 0))
    C["spin_showbasis_s1_n6_sz0"] = ("6 spins 1, Sz=0 (spin 3/2 is not implemented by GenericSpinChainShowBasis)", spin_chain_dimension(6, 2, 0))
    return C


def render(name, entry):
    desc, val = entry
    lines = [f"# {name}: {desc}", "# generated by tests/oracles/dimensions.py; do not edit"]
    if isinstance(val, int):
        lines.append(f"COUNT {val}")
    else:
        lines.extend(val)
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", metavar="DIR")
    ap.add_argument("--check", metavar="DIR")
    a = ap.parse_args()
    C = cases()
    if a.write:
        Path(a.write).mkdir(parents=True, exist_ok=True)
        for name, entry in C.items():
            (Path(a.write) / f"{name}.txt").write_text(render(name, entry))
        print(f"wrote {len(C)} expected files to {a.write}")
    if a.check:
        bad = 0
        for name, entry in C.items():
            p = Path(a.check) / f"{name}.txt"
            if not p.exists() or p.read_text() != render(name, entry):
                bad += 1
                print(f"MISMATCH {p}")
        extra = set(p.stem for p in Path(a.check).glob("*.txt")) - set(C)
        for e in sorted(extra):
            bad += 1
            print(f"NOT GENERATED BY THE ORACLE: {e}.txt")
        print(f"{len(C)} cases, {bad} mismatches")
        sys.exit(1 if bad else 0)
    if not a.write and not a.check:
        for name, entry in C.items():
            print(render(name, entry))


if __name__ == "__main__":
    main()
